goplus/igop

ops.go

golang.org/x/tools v0.1.10 ssa.OpBin token.SHL/SHR remove ssa.Convert

opSHL/opSHR use asInt

---

cmd/internal/run/run.go
context.go
visit.go

cmd/gossa: run add flag -dump -trace

---

cmd/qexp/api.go
cmd/qexp/main.go

fix: custome  -> customer

---

context.go
interp_test.go
ops.go
print.go
value.go

fix https://github.com/goplus/gossa/issues/59

compatible builtin print/println/panic

---

context.go
rtypes.go
visit.go

fix: some spell error

---

context.go
interp_test.go

explicit context to clear override function for maintaining more easy

explicit context to clear override function

---

package.go

easy for maintaining the fields of the Package struct

extract package merge function

---

go.mod
go.sum
opblock.go

dynamic func call check create by makeFunc and fast call
https://github.com/visualfc/funcval
```
package main
func main() {
var fib func(n int) int
fib = func(n int) int {
if n < 2 {
return n
}
return fib(n-2) + fib(n-1)
}
println(fib(35))
}
```

optimize and fast closure call

---

basic/basic.go
binop.go
binop_gen.go
cmd/gossatest/main.go
interp_test.go
opblock.go

1. static check op const `+ - * / % & | ^ &^  < <= > >=`
2. named basic type
fast op  <https://github.com/goplus/gossa/tree/binop/basic>
```
type MyInt int
i := MyInt(100)
t := basic.TypeOf(i)
basic.Int(i) // int
basic.Make(t,100) // MyInt interface{}
```
3. TODO impl static check op `== != << >>`

optimize ssa.BinOp ( add sub mul quo rem and or xor andnot lss leq gtr geq )

---

interp.go
opblock.go
visit.go

function/frame stack [ result[0], result[1] ..., args[0], args [1] ,..., env[0], env[1] ..., data[0], .... ]
fast fibish.go
```
func f(x int) (int, int) {
if x < 3 {
return 0, x
}
a, b := f(x - 2)
c, d := f(x - 1)
return a + d, b + c
}
```

frame: change results to stack from []register

---

binop.go
binop_gen.go
interp_test.go

```
var a int = 10
var b int = 20
println(a+b) 
```
```
*ssa.BinOp           t0 = 10:int + 20:int                         	int
*ssa.Call            t1 = println(t0)                             	()
```

binop: static check x const and y const

---

context.go
interp.go

ctx.Run => ctx.RunPkg
inerp := gossa.NewInterp()
interp.Run("init")
interp.Run("main")

NewInterp: remove call init

---

repl.go
repl_test.go

for expr -> func() { for expr }()

fix #126, repl for/if/switch/select expr

---

cmd/internal/run/run.go
cmd/internal/test/test.go
context.go
interp_test.go
testdata/msg/notags.go
testdata/msg/tags.go

support #147
- LoadDir use Context.BuildContxt
- igop run/test add flag -tags

build context

---

binop_x.go
go.mod
go.sum
interp.go
interp_test.go
opblock.go
ops.go

reflectx: struct(has underscore) and interface implement rtype.equal
fix #155

fix equal for struct/interface

---

cmd/internal/test/test.go
context.go
importer.go
package.go
pkg/gen.go
pkg/go114_pkgs.go
pkg/go115_pkgs.go
pkg/go116_pkgs.go
pkg/go117_pkgs.go
pkg/go118_pkgs.go

support load testing/fstest(iotest,quick) from source.

lookupPath backup build.Import load std package

---

cmd/internal/test/test.go
context.go
driver.go
errors.go

`go list -deps -e .`
support https://github.com/goplus/igop/issues/148

add new ListDirver for support module/vendor

---

context.go
interp.go
interp_test.go
runtime_go117.go
runtime_go118.go

impl https://github.com/goplus/igop/issues/169
igop.Mode set ExperimentFuncForPC
```
pc := reflect.ValueOf(fn).Pointer()
fn := runtime.FuncForPC(pc)
fmt.Println(fn.Name(), fn.Entry())
fmt.Println(fn.FileLine(fn.Entry))
```

experiment: hook (reflect.Value).Pointer and runtime.FuncForPC

---

pkg/gen.go
pkg/go114_pkgs.go
pkg/go115_pkgs.go
pkg/go116_pkgs.go
pkg/go117_pkgs.go
pkg/go118_pkgs.go
pkg/go119_pkgs.go

igop default load net/rpc and net/rpc/jsonrpc from source
igop hook reflect api
- reflect.Type.Method => reflectx.MethodByIndex
- reflect.Type.MethodByName => reflectx.MethodByName

pkg: default remove net/rpc net/rpc/jsonrpc

---

builtin.go
cmd/igoptest/main.go
errstring.go
errstring_go120.go
frame.go
interp_go117_test.go
opblock.go
repl.go

- error message diff for go1.20
- unsafe.SliceData
- unsafe.String
- unsafe.StringData

support go1.20

---

cmd/internal/export/export.go
cmd/internal/export/loader.go
interp_test.go

fix #203 
igop export -tags mytags

export: support -tags for build tags

---

README.md

- add a Go+ demo in README.md
- format README.md

Add a Go+ demo in README.md

---

rtypes.go
typeparam_test.go
types_go117.go
types_go118.go

fix https://github.com/goplus/igop/issues/223

fix prebuild package fields has typeargs

---

go.mod
gopbuild/build.go
gopbuild/build_test.go
pkg/github.com/qiniu/x/errors/export.go

gopbuild: add github.com/qiniu/x/errors for Go+ errors handling

---

builtin.go
cmd/internal/run/run.go
interp.go
interp_test.go
opblock.go
ops.go
runtime.go
visit.go

RunFunc: check error type

---

context.go
go.mod
go.sum
interp.go
opblock.go
runtime.go
visit.go
xtypes.go

(*Context).UnsafeRelease()
(*Interp).UnsafeRelease()

support creator multiple interp

---

go.mod
go.sum
visit.go

fix https://github.com/goplus/igop/issues/261

visit: exportedTypeHack for golang.org/x/tools v0.16
